CREATE TABLE IF NOT EXISTS matricula (
    id                BIGINT       AUTO_INCREMENT PRIMARY KEY,
    cpf               VARCHAR(14)  NOT NULL,
    nome              VARCHAR(255),
    curso             VARCHAR(255),
    data_nascimento   DATE,
    nome_contato      VARCHAR(255),
    telefone_contato  VARCHAR(20),
    parentesco        VARCHAR(50),
    amigdalite        TINYINT(1)   DEFAULT NULL,
    bronquite         TINYINT(1)   DEFAULT NULL,
    diabetes          TINYINT(1)   DEFAULT NULL,
    sinusite          TINYINT(1)   DEFAULT NULL,
    palpitacao        TINYINT(1)   DEFAULT NULL,
    hemorragia        TINYINT(1)   DEFAULT NULL,
    faltadear         TINYINT(1)   DEFAULT NULL,
    convulsao         TINYINT(1)   DEFAULT NULL,
    sarampo           TINYINT(1)   DEFAULT NULL,
    coqueluche        TINYINT(1)   DEFAULT NULL,
    rubeola           TINYINT(1)   DEFAULT NULL,
    catapora          TINYINT(1)   DEFAULT NULL,
    caxumba           TINYINT(1)   DEFAULT NULL,
    tuberculose       TINYINT(1)   DEFAULT NULL,
    fisica            TINYINT(1)   DEFAULT NULL,
    auditiva          TINYINT(1)   DEFAULT NULL,
    visual            TINYINT(1)   DEFAULT NULL,
    intelectual       TINYINT(1)   DEFAULT NULL,
    crecimento        TEXT,
    desenvolvimento   TEXT,
    tratamento        TEXT,
    medicacao         TEXT,
    cirurgia          TEXT,
    alergia           TEXT,
    observacao        TEXT,
    autorizacao_imagem TINYINT(1)  DEFAULT 0,
    bloqueado         TINYINT(1)   DEFAULT 0,
    UNIQUE KEY uq_cpf (cpf)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
